name: BTVault Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.jpg"
      - "**/*.png"
      - ".github/assets/**"

jobs:
  Derle:
    runs-on: ubuntu-latest
    steps:
      - name: Kaynak Kodunu Kontrol Et
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Build Branch'ini Kontrol Et
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Eski Derlemeleri Temizle
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: JDK 21 Ayarla
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          cache: gradle

      - name: Android SDK Ayarla
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Eklentileri Derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/
          cp build/plugins.json $GITHUB_WORKSPACE/builds/

      - name: Derlemeleri Yukle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "${{ github.sha }} icin derleme" || exit 0
          git push --force
